
# collections helps us count the occurences of each item 
import collections

seq = "CGATGCCGCATCTCCGCATCCTCGGCAACGACGGTCGAGCTTTGTGGAGTGGTGACGCGGAGAAATTTGACTTTTGGGGGTCGGGAATTGCTAACACTAACCCCTCTATTGCCGGTAAATAGTTGCCGCAGGATAGGTTACTTATGCGACTCTAGGCCCCGTTAAGACAAAAGGACGCGTCCTGCTGGGACTCTATGGGTCTCGCCACGCTTCTTTCCACCACCTGATAAAACATGATAGATTAAGTATCAGCCTTGCATATTTTCGTCAGTAATAAAGCACGCATCCACACTCGGGGGCCTATCTCTGGCTCACGCTGTACTATCATCCGGGTGAACGACACGTCCTCGATTGGTCTTCCCCAATGATCGATCCAGAACCCTCTCCTCACGGGGAGACCGCGTGCTGCAACATATTCGGCTGCAAAATAATTAGACTCAATCTCAAATCGCACACGTGAGACACGAATAAGCAGTGGGCCATCCTCACAGCGCCCATAGTCAAATCCTTGGCACTCACGTCACCTAGCAGACATCCGCTAGGAAGGTGAGGTCGACTCAGTTAAACTTACGCACCCAAGAGTGCCATCCGACTTCGGAGGCTAATCCACTGATTCTGCGGACACTGGGATCTAACTTTCTCAGCACACGCCCACCAGAGAACGGTGCACAAGAAGCTTATCACGTCCACCAGGAATGGAGGGCGTAGCTGACCGACTACTTGGTGTTATTAGCACTTTGCACCAGGCTCTAGCTGTGCCAAGTCTTCGAGCATTTACCCTAAGTTGTTAGTGGCCATAC"

# we need the output in this order
Nucleotides = ["A", "C", "G", "T"]


# function to count the occurences
def countFrequency(seq):
  count = dict(collections.Counter(seq))

  # iterate through the list to get the order for the output
  for i in Nucleotides:
    print(count[i], end=" ")


# prints occurences of each item 
countFrequency(seq)

# Output:
# 199 226 188 187 
